### ISSUE TITLE
[EPIC] Manage users

### ISSUE THREAD

**Issue by itsdyzoon** [baktygaliyevv/uwe-hrms-app#5]
### Description
On this screen admins should be able to manage users. Upon entrance to the screen table with all users is rendered, each row containing user phone number, role (with ability to change it with a selector), edit button (bringing a menu to edit users (see "Edit menu")) and delete button.
Above the table there should also be a "Add user" button, sending user to the "Edit menu" submenu.

#### Edit menu 
Separate menu to add/edit users. If entrypoint is Edit button, several key inputs should be prefilled and maybe even disabled. If the entrypoint is "Add user" all inputs should be empty ready to be filled out. Upon clicking "Save" either existing user should be edited in database or new user should be added, depending on the entrypoint to this screen.

![Untitled-2023-12-11-1612](https://github.com/itsdyzoon/uwe-hrms-app/assets/24205205/8054d3a0-5d61-43e0-b693-2ff6d7365146)

### Entrypoint

"Manage users" button on the main screen
### Interface

**Manage Users Menu:**
Purpose: Serves as the entry point for accessing user administration functionalities.

**User Creation:**
Purpose: Allows administrators to create new user accounts.

**Edit User Menu:**
Purpose: Enables administrators to modify existing user profiles.

**Delete User Menu:**
Purpose: Facilitates the removal of user accounts.
 
### Actions

**Manage Users Menu:**
Behavior: Clicking on the "Manage Users" menu should open a dedicated section with options for user-related actions.

**User Creation:**
Behavior: Clicking on the "Create User" option should open a form or workflow for entering new user details, including username, phone, password, and any relevant role information.

**Edit User Menu:**
Behavior: Clicking on the "Edit User" menu should open a screen where administrators can select a user to edit and make necessary modifications to user details.

**Delete User Menu:**
Behavior: Clicking on the "Delete User" menu should open a confirmation dialog or workflow, ensuring administrators confirm their intent to delete a specific user account. 

### Subtasks

- [x] https://github.com/itsdyzoon/uwe-hrms-app/issues/6
- [x] https://github.com/itsdyzoon/uwe-hrms-app/issues/7
- [x] https://github.com/itsdyzoon/uwe-hrms-app/issues/8
